apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: vishnusk/flask-rce 
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flask-app-svc
  name: flask-app-svc
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 5000
  selector:
    app: flask-app
  type: LoadBalancer
